### ISSUE TITLE
Code not show

### ISSUE THREAD

**Issue by xub** [shangguokan/SGKBarcodeBundle#4]
why the code below the image is not displayed ?

**Comment by shangguokan** [comment]
what means "code below the image", 
what code and what image?

**Comment by xub** [comment]
Bar codes show the numbers below the barcode , not shown here

**Comment by shangguokan** [comment]
I think i understand what you want to say.
yes, the code don't show below the barcode, but you can add it by yourself.
you can choose Html format and add the code below html code
